spring:
 build: ./spring
 ports:
   - "8080:8080"
 links:
   - mysql
 tty: true

mysql:
 image: mysql:5.7
 ports:
    - "3306:3306"
 volumes:
    - ./spring/var/lib/mysql:/var/lib/mysql
 environment:
    - MYSQL_ROOT_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic

nginx:
 build: ./nginx
 ports:
   - "80:80"
 links:
   - spring

